#!/usr/bin/env bash
# Quick setup script for new projects
# Usage: ./setup-project.sh [project-name]

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

PROJECT_NAME="${1:-}"

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Claude Autonomous Builder - Project Setup               ║${NC}"
echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo ""

# Get project name if not provided
if [ -z "$PROJECT_NAME" ]; then
    read -p "Enter project name: " PROJECT_NAME
fi

if [ -z "$PROJECT_NAME" ]; then
    echo -e "${RED}Error: Project name is required${NC}"
    exit 1
fi

PROJECT_DIR="$HOME/projects/$PROJECT_NAME"

echo -e "${GREEN}Setting up project: ${PROJECT_NAME}${NC}"
echo -e "${YELLOW}Location: ${PROJECT_DIR}${NC}"
echo ""

# Create project directory
if [ -d "$PROJECT_DIR" ]; then
    echo -e "${YELLOW}Warning: Directory already exists${NC}"
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
else
    mkdir -p "$PROJECT_DIR"
    echo -e "${GREEN}✓ Created directory${NC}"
fi

cd "$PROJECT_DIR"

# Initialize git
if [ ! -d ".git" ]; then
    git init
    echo -e "${GREEN}✓ Initialized git repository${NC}"
else
    echo -e "${YELLOW}⚠ Git already initialized${NC}"
fi

# Check for global config
GLOBAL_CONFIG="$HOME/.claude-global"

if [ -d "$GLOBAL_CONFIG" ]; then
    echo -e "${GREEN}✓ Found global config at ${GLOBAL_CONFIG}${NC}"

    # Create symlink
    if [ -L ".claude" ] || [ -d ".claude" ]; then
        echo -e "${YELLOW}⚠ .claude already exists${NC}"
        read -p "Replace it? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -rf .claude
            ln -s "$GLOBAL_CONFIG" .claude
            echo -e "${GREEN}✓ Linked to global config${NC}"
        fi
    else
        ln -s "$GLOBAL_CONFIG" .claude
        echo -e "${GREEN}✓ Linked to global config${NC}"
    fi
else
    echo -e "${YELLOW}⚠ Global config not found at ${GLOBAL_CONFIG}${NC}"
    echo ""
    echo "Would you like to:"
    echo "  1. Set up global config (recommended)"
    echo "  2. Copy config to this project only"
    echo "  3. Skip (manual setup)"
    read -p "Choice (1-3): " -n 1 -r SETUP_CHOICE
    echo

    case $SETUP_CHOICE in
        1)
            echo -e "${BLUE}Setting up global config...${NC}"
            BUILDER_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
            ln -s "$BUILDER_PATH/.claude" "$GLOBAL_CONFIG"
            ln -s "$GLOBAL_CONFIG" .claude
            echo -e "${GREEN}✓ Global config created and linked${NC}"
            ;;
        2)
            BUILDER_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
            cp -r "$BUILDER_PATH/.claude" .
            .claude/scripts/init-knowledge-base.sh
            echo -e "${GREEN}✓ Config copied to project${NC}"
            ;;
        *)
            echo -e "${YELLOW}⚠ Skipping config setup${NC}"
            ;;
    esac
fi

# Create GitHub repo
echo ""
echo -e "${BLUE}GitHub Repository Setup${NC}"

if command -v gh &> /dev/null; then
    read -p "Create GitHub repository? (Y/n): " -n 1 -r CREATE_REPO
    echo
    if [[ ! $CREATE_REPO =~ ^[Nn]$ ]]; then
        read -p "Public or private? (public/private): " REPO_VISIBILITY
        REPO_VISIBILITY=${REPO_VISIBILITY:-public}

        gh repo create "$PROJECT_NAME" \
            --"$REPO_VISIBILITY" \
            --source=. \
            --remote=origin \
            --description "Built with Claude Autonomous Builder"

        if [ $? -eq 0 ]; then
            echo -e "${GREEN}✓ GitHub repository created${NC}"
        else
            echo -e "${YELLOW}⚠ GitHub repository creation failed${NC}"
        fi
    fi
else
    echo -e "${YELLOW}⚠ gh CLI not installed. Skipping GitHub repo creation.${NC}"
    echo "  Install with: brew install gh"
fi

# Create initial README
if [ ! -f "README.md" ]; then
    cat > README.md << EOF
# $PROJECT_NAME

Built with [Claude Autonomous Builder](https://github.com/yourusername/claude-autonomous-builder)

## Getting Started

This project was generated by the autonomous orchestrator. See \`docs/\` for:
- \`PRD.md\` - Product requirements
- \`ARCHITECTURE.md\` - System architecture
- \`METRICS.md\` - Project metrics
- \`LEARNING-REPORT.md\` - Learnings extracted

## Development

\`\`\`bash
# Install dependencies
npm install

# Run tests
npm test

# Run with coverage
npm run test:coverage
\`\`\`

## Documentation

See \`docs/\` directory for comprehensive documentation.
EOF
    echo -e "${GREEN}✓ Created README.md${NC}"
else
    echo -e "${YELLOW}⚠ README.md already exists${NC}"
fi

# Summary
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   Setup Complete! 🎉                                       ║${NC}"
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo ""
echo -e "${YELLOW}Project:${NC} $PROJECT_NAME"
echo -e "${YELLOW}Location:${NC} $PROJECT_DIR"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo ""
echo -e "  1. ${YELLOW}cd $PROJECT_DIR${NC}"
echo -e "  2. Open in your IDE: ${YELLOW}code .${NC}"
echo -e "  3. In Claude Code, run:"
echo ""
echo -e "     ${GREEN}/orchestrator${NC} \"Your detailed project description\""
echo ""
echo -e "  Examples:"
echo -e "     ${GREEN}/orchestrator${NC} A REST API with JWT auth and PostgreSQL"
echo -e "     ${GREEN}/orchestrator${NC} A React todo app with TypeScript"
echo -e "     ${GREEN}/orchestrator${NC} A CLI tool for database migrations"
echo ""
echo -e "${BLUE}Learning features:${NC}"
echo -e "     ${GREEN}/patterns recommend${NC} \"Your feature\" - Search patterns"
echo -e "     ${GREEN}/reflect${NC} - Trigger learning (automatic by default)"
echo -e "     ${GREEN}/optimize${NC} - Optimize thresholds (after 5+ projects)"
echo ""
echo -e "${YELLOW}Documentation:${NC}"
echo -e "  - Quick start: https://github.com/yourusername/claude-autonomous-builder"
echo -e "  - Learning system: LEARNING-SYSTEM-SUMMARY.md"
echo ""
